version: '3.9'

services:
  dash:
    command: python3 main.py
    image: appprediction:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Test.Dockerfile
    ports:
      - 8100:70
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=70